import traceback

try:
# filling the code
except Exception as e:

    with open("trace.txt", "w") as f:
        f.write(str(e))

